/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LFG } from "./LFG";
export * as factories from "./factories";
export { LFG__factory } from "./factories/LFG__factory";
